// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Timestamp from public import google/protobuf/timestamp.proto
type Timestamp = timestamp.Timestamp

type User struct {
	Username             string               `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type RegisterUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterUserResponse struct {
	Username             string               `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterUserResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type UserStreamRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserStreamRequest) Reset()         { *m = UserStreamRequest{} }
func (m *UserStreamRequest) String() string { return proto.CompactTextString(m) }
func (*UserStreamRequest) ProtoMessage()    {}
func (*UserStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStreamRequest.Unmarshal(m, b)
}
func (m *UserStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStreamRequest.Marshal(b, m, deterministic)
}
func (m *UserStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStreamRequest.Merge(m, src)
}
func (m *UserStreamRequest) XXX_Size() int {
	return xxx_messageInfo_UserStreamRequest.Size(m)
}
func (m *UserStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserStreamRequest proto.InternalMessageInfo

func (m *UserStreamRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserStreamResponse struct {
	User                 []*User  `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserStreamResponse) Reset()         { *m = UserStreamResponse{} }
func (m *UserStreamResponse) String() string { return proto.CompactTextString(m) }
func (*UserStreamResponse) ProtoMessage()    {}
func (*UserStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStreamResponse.Unmarshal(m, b)
}
func (m *UserStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStreamResponse.Marshal(b, m, deterministic)
}
func (m *UserStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStreamResponse.Merge(m, src)
}
func (m *UserStreamResponse) XXX_Size() int {
	return xxx_messageInfo_UserStreamResponse.Size(m)
}
func (m *UserStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserStreamResponse proto.InternalMessageInfo

func (m *UserStreamResponse) GetUser() []*User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*RegisterUserRequest)(nil), "user.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "user.RegisterUserResponse")
	proto.RegisterType((*UserStreamRequest)(nil), "user.UserStreamRequest")
	proto.RegisterType((*UserStreamResponse)(nil), "user.UserStreamResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x3d, 0x4f, 0xf3, 0x30,
	0x10, 0xc7, 0xeb, 0xa7, 0x7d, 0x50, 0x7a, 0x91, 0x90, 0x30, 0x95, 0x30, 0x1e, 0x20, 0xca, 0x94,
	0x29, 0x91, 0x02, 0x0b, 0x23, 0x42, 0x6c, 0x0c, 0x28, 0xc0, 0x8c, 0xdc, 0xf4, 0x88, 0x22, 0x35,
	0x75, 0xf0, 0x39, 0xf0, 0x01, 0xf8, 0x14, 0x7c, 0x5b, 0x14, 0xbb, 0x01, 0x2a, 0x3a, 0xf0, 0xb2,
	0xf9, 0x5e, 0xfe, 0xfe, 0xdd, 0xff, 0x0e, 0xa0, 0x23, 0x34, 0x69, 0x6b, 0xb4, 0xd5, 0x7c, 0xd2,
	0xbf, 0xe5, 0x71, 0xa5, 0x75, 0xb5, 0xc4, 0xcc, 0xe5, 0xe6, 0xdd, 0x43, 0x66, 0xeb, 0x06, 0xc9,
	0xaa, 0xa6, 0xf5, 0x6d, 0x31, 0xc1, 0xe4, 0x8e, 0xd0, 0x70, 0x09, 0x41, 0x2f, 0x58, 0xa9, 0x06,
	0x05, 0x8b, 0x58, 0x32, 0x2d, 0xde, 0x63, 0x3e, 0x83, 0xff, 0xd8, 0xa8, 0x7a, 0x29, 0xfe, 0xb9,
	0x82, 0x0f, 0xf8, 0x19, 0x40, 0x69, 0x50, 0x59, 0x5c, 0xdc, 0x2b, 0x2b, 0x26, 0x11, 0x4b, 0xc2,
	0x5c, 0xa6, 0x9e, 0x97, 0x0e, 0xbc, 0xf4, 0x76, 0xe0, 0x15, 0xd3, 0x75, 0xf7, 0xb9, 0x8d, 0x4b,
	0xd8, 0x2f, 0xb0, 0xaa, 0xc9, 0xa2, 0xe9, 0xe1, 0x05, 0x3e, 0x76, 0x48, 0xf6, 0x17, 0x33, 0x48,
	0x08, 0x5a, 0x45, 0xf4, 0xac, 0xcd, 0x42, 0x8c, 0xbd, 0x62, 0x88, 0xe3, 0x17, 0x06, 0xb3, 0x4d,
	0x0a, 0xb5, 0x7a, 0x45, 0xf8, 0x67, 0xab, 0xe3, 0x9f, 0x58, 0xcd, 0x60, 0xaf, 0x87, 0xdf, 0x58,
	0x83, 0xaa, 0xf9, 0x86, 0xd1, 0xf8, 0x14, 0xf8, 0x67, 0xc1, 0x7a, 0xe6, 0x23, 0x70, 0xf7, 0x14,
	0x2c, 0x1a, 0x27, 0x61, 0x0e, 0xa9, 0x3b, 0xb4, 0x73, 0xe5, 0xf2, 0xf9, 0x2b, 0x83, 0xd0, 0xc9,
	0xd0, 0x3c, 0xd5, 0x25, 0xf2, 0x0b, 0x08, 0x06, 0xef, 0xfc, 0xd0, 0x77, 0x6f, 0xd9, 0xb8, 0x94,
	0xdb, 0x4a, 0x1e, 0x19, 0x8f, 0xf8, 0x25, 0xec, 0xf6, 0x99, 0xab, 0x9a, 0xac, 0x1f, 0x87, 0x1f,
	0x7c, 0x80, 0x37, 0x1c, 0x49, 0xf1, 0xb5, 0x30, 0x7c, 0x73, 0x3d, 0x9a, 0xef, 0xb8, 0x1d, 0x9d,
	0xbc, 0x05, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xd7, 0x69, 0x83, 0xa0, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	//注册用户
	Register(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	//用户列表(服务端推送流)
	UserListStream(ctx context.Context, in *UserStreamRequest, opts ...grpc.CallOption) (*UserStreamResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Register(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserListStream(ctx context.Context, in *UserStreamRequest, opts ...grpc.CallOption) (*UserStreamResponse, error) {
	out := new(UserStreamResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/UserListStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	//注册用户
	Register(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	//用户列表(服务端推送流)
	UserListStream(context.Context, *UserStreamRequest) (*UserStreamResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Register(ctx context.Context, req *RegisterUserRequest) (*RegisterUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUserServiceServer) UserListStream(ctx context.Context, req *UserStreamRequest) (*UserStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserListStream not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserListStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserListStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UserListStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserListStream(ctx, req.(*UserStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _UserService_Register_Handler,
		},
		{
			MethodName: "UserListStream",
			Handler:    _UserService_UserListStream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
